## ЧАСТЬ I. Решите задания используя только стандартные методы Python 3

### 1. Импортируйте число e из библиотеки math и выведите его с округлением до 4 цифр после запятой

In [7]:
from math import e 
round(e, 4)

2.7183

### 2. Вычислите целую часть результата деления 100 на 7. Убедитесь, что её тип – целое число.

In [8]:
a = 100 // 7
print(a)
isinstance(a, int)

14


True

### 3. Создайте список с квадратами целых чисел от 12 до 4 с шагом 2 не делящимися на 5.

In [9]:
list1 = [i * i for i in range(12, 4, -2) if i * i % 5 != 0]
print(list1)

[144, 64, 36]


### 4.	Отсортируйте полученный в пункте 3 список относительно модуля разницы между элементами этого списка и числом 50.

In [10]:
sorted(list1, key = lambda i: abs(i - 50))

[64, 36, 144]

### 5. Создайте множество (set) содержащее все 26 маленькие буквы латинского алфавита.

In [11]:
import string
s = set()
for i in string.ascii_lowercase:
    s.add(i)
print(s)

{'f', 'e', 'g', 'a', 'z', 'j', 'x', 'n', 'h', 'u', 'w', 'v', 'd', 'q', 'm', 'k', 't', 'y', 'o', 'c', 's', 'r', 'i', 'b', 'l', 'p'}


### 6.	Создайте список, содержащий числа с повторениями. Используя словарь, подсчитайте, сколько раз каждое число встречалось в этом списке, и напечатайте содержимое словаря

In [ ]:
rep = [3, 3, 0, 1, 3, 3, 0, 0, 3, 1, 4, 2, 3, 2, 3]
dict = {}
for i in rep:
    if i not in dict:
        dict[i] = rep.count(i)
print(dict)

### 7. Реализуйте функцию от трёх аргументов a, b и c находящую вещественные корни уравнения ax2 + bx + c = 0, с нулевыми значениями аргументов по умолчанию

In [13]:
import math

def fun(a = 0, b = 0, c = 0):
    D = b ** 2 - 4 * a * c
    if D > 0:
        x1 = (-b + math.sqrt(D)) / (2 * a)
        x2 = (-b - math.sqrt(D)) / (2 * a)
        return x1, x2
    elif D == 0:
        x = - b / (2 * a)
        return x
    else:
        print("Нет вещественных корней")

In [14]:
fun(a = 8, b = 4, c = 2)

Нет вещественных корней


In [15]:
fun(a = 3.2, b = -7.8, c = 1)

(2.3017327156977156, 0.13576728430228405)

### 8.	Реализуйте класс Point с полями x,y заполняемыми в конструкторе

In [16]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y   

### 9. Реализуйте класс Circle наследника класса Point с дополнительным полем r и методом inside(p) проверяющим, что круг содержит точку p.

In [ ]:
import math

class Circle(Point):
    def __init__(self, radius, x = 0, y = 0):
        super().__init__(x, y)
        self.radius = radius
        
    def inside(self, p):
        if math.sqrt((p.x**2 + p.y**2)) <= self.radius:
            print("Круг содержит точку P")
        else:
            print("Круг не содержит точку P")

In [18]:
p1 = Point(2,5)            
b = Circle(8)
b.inside(p1)

Круг содержит точку P


### 10. Реализуйте метод класса Point, принимающий другой объект класса Point и вычисляющий эвклидово расстояние до него

In [19]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y   
        
    def euс_dist(self, other_point):
        return ((other_point.x - self.x) ** 2
            + (other_point.y - self.y) ** 2) ** 0.5

In [149]:
p1 = Point(2, 5)
p2 = Point(4, 6)
p1.euс_dist(p2)

2.23606797749979

## ЧАСТЬ II. Решите задачи используя библиотеку NumPy

### 11. Создайте матрицу 4x4, значения элементов которой варьируются от 0 до 15

In [20]:
import numpy as np

In [21]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 12. Найдите индексы ненулевых элементов из списка [1,2,0,0,4,0,5,7,8,0,0,0]

In [22]:
np.nonzero([1,2,0,0,4,0,5,7,8,0,0,0])

(array([0, 1, 4, 6, 7, 8], dtype=int64),)

### 13. Создайте единичную матрицу размера 3х3

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 14. Создайте матрицу 10х10, заполните её случайными значениями и найдите максимальный и минимальный элементы

In [24]:
from numpy import random
m = np.random.random((10,10))
print(m.min(), m.max())

0.0032908513888265656 0.9912998200223995


### 15. Создайте матрицу 5х5 и расположите в ней числа 1, 2, 3, 4 под главной диагональю

In [27]:
np.diag(np.arange(1, 5), k =-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 16. Перемножьте случайные матрицы размерностей 5х3 и 3х2

In [28]:
mul = np.dot(np.random.random((5,3)), np.random.random((3,2)))
print(mul)

[[0.94049131 1.02009922]
 [0.94744682 1.06336704]
 [0.75647925 0.96668671]
 [0.75743381 0.81150428]
 [1.25682371 1.36153752]]


### 17. Найдите число из списка t, наиболее близкое по величине к числу a

In [29]:
a = 2.39
t = [0, 1, 1.2, 2, 3, 9]

min(t, key = lambda i: abs(i - a))

2

### 18. Создайте массив из 10 элементов и поменяйте значение его наибольшего элемента на 0 

In [30]:
mas = np.random.random(10)
print(mas)
mas[mas.argmax()] = 0
print(mas)

[0.22780391 0.03253253 0.25234024 0.51177241 0.83015467 0.3060403
 0.52934879 0.20299608 0.47093096 0.05186876]
[0.22780391 0.03253253 0.25234024 0.51177241 0.         0.3060403
 0.52934879 0.20299608 0.47093096 0.05186876]


### 19. Создайте матрицу 5x5 и поменяйте в ней местами 2 и 3 строку

In [31]:
fiv = np.arange(25).reshape(5,5)
print(fiv)
fiv[[1,2]] = fiv[[2,1]]
print(fiv)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 20. Создайте случайную целочисленную матрицу и найдите наиболее часто встречающийся в ней элемент

In [32]:
i = np.random.randint(0, 5, size = (10,10))
print(i)
i = i.flatten()
np.bincount(i).argmax()

[[0 4 4 4 0 3 4 2 3 2]
 [4 3 2 4 4 4 2 0 2 1]
 [2 1 0 0 3 1 2 3 3 2]
 [3 4 2 3 0 0 4 2 1 0]
 [1 2 0 1 4 2 2 0 2 1]
 [4 3 0 1 2 0 1 2 0 0]
 [0 3 2 2 1 0 1 2 2 2]
 [3 4 1 3 1 2 4 1 2 1]
 [0 2 3 0 2 0 4 4 2 0]
 [0 1 4 4 3 1 1 1 1 2]]


2

## Часть III. Прочитайте краткий мануал по библиотеке pandas и выполните оставшиеся задания

Pandas - это библиотека Python, предоставляющая широкие возможности для анализа данных. С ее помощью очень удобно загружать, обрабатывать и анализировать табличные данные с помощью SQL-подобных запросов. В связке с библиотеками Matplotlib и Seaborn появляется возможность удобного визуального анализа табличных данных.


Для использования библиотек их необходимо импортировать, что можно сделать с помощью команды import. После ключевого слова import указывается название библиотеки, а после as - ее краткое название (алиас), которое мы будем использовать в коде для краткого обозначения этой библиотеки.

In [0]:
import pandas as pd

Основными структурами данных в Pandas являются классы Series и DataFrame. Первый из них представляет собой одномерный индексированный массив данных некоторого фиксированного типа (его можно интеерпретировать как индексированный столбец таблицы). Второй - это двухмерная структура данных, представляющая собой таблицу, каждый столбец которой содержит данные одного типа. Можно представлять её как словарь объектов типа Series. Структура DataFrame отлично подходит для представления реальных данных: строки соответствуют признаковым описаниям отдельных объектов, а столбцы соответствуют признакам.

## Чтение из файла и первичный анализ
Чаще всего, данные, которые мы будем анализировать, готовить  и использовать для обучения моделей, не формируются самостоятельно, а берутся из готового дататсета. Рассмотрим чтение датасета (DataFrame) из файла с расширением csv. В качестве примера возьмем titanic_train.csv, который содержить данные о пассажирах Титаника. Полный датасет titanic был разделен на 2 части - тренировочную и тестовую. Именно с тренировочной частью мы и будем работать. Датасет titanic предоставлен в рабочей папке Лаб_1, а также вы можете его скачать (titanic_train.csv) по ссылке https://www.kaggle.com/tedllh/titanic-train#titanic_train.csv. Если вы работаете на платформе Goggle Colab, необходимо сделать upload файла в вашу рабочую директорию ( в меню ноутбука слева  найти и перейти на Files, нажать Upload и выбрать файл для загрузки)

Внимание! Проверьте, что файл находиться в папке content, если его там нет, то нажмите на нее правой кнопкой и upload. 


###Чтение данных

In [ ]:
Для чтения csv файла используем функцию pd.read_csv

In [ ]:
import pandas as pd
df = pd.read_csv('titanic_train.csv')

Посмотрим тип переменной df

In [5]:
type(df)

pandas.core.frame.DataFrame

### Первичный анализ

После того, как мы считали данные, посмотрим первые несколько записей датафрейма (если в скобках после функции head не указать нужное количество записей, то по умолчанию будут выведены первые 5 записей датафрейма). Если вместо таблицы вы видите  "кашу" из данных, разделенных ";", значит, ваш csv файл использует в качестве разделителя ";", а не ",". И для корректного чтения данных, нужно задать разделитель в функции чтения, например df = pd.read_csv('proba.csv', sep=";")

In [6]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

Давайте посмотрим, что это за данные. Достаточно часто датасеты имеют краткое описание содержимого. Например, что означает тот или иной столбец, какие значения используются для заполнения и т.д. Или значения признаков интуитивно понятны. В нашем случае, мы имеем следующие данные:
каждая строка - это сведения об отдельном пассажире. Строка содержит:
*   PassengerId - идентификатор пассажира (проще говоря, порядковый номер строки)
*   Survived - признак, выжил ли пассажир после крушения (0 - погиб, 1 - выжил)
*   Pclass - в каком классе ехал пассажир (1, 2 или 3)
*   Name - имя пассажира
*   Sex - пол (male - мужской, female - женский)
*   Age - возраст
*   SibSp - количество родственников (по горизонтали - супруг, братья, сестры) на борту
*   Parch - количество родственников (по вертикали - родители, дети) на борту 
*   Ticket - номер билета
*   Fare - цена билета
*   Cabin - номер каюты
*   Embarked - порт посадки (C — Cherbourg, Q — Queenstown, S — Southampton)





Команда shape() показывате размерность датафрейма

Мы видим, что в нашем датафрейме 891 строка (то есть, сведения о 891 пассажире) и 12 столбцов признаков

In [0]:
df.shape

Команда columns.values() показывате название всех признаков

In [0]:
df.columns.values

Также полезно посмотреть метод info, который показывает краткую статистику по набору данных

In [0]:
df.info()

Можно увидеть, что не все признаки у нас заполнены в каждой строке,для некоторых признаков есть пропуски. Например, у нас 891 строка, а Age (возраст) заполнен только в 714 строках. Совсем мало значений в столбце Cabin. 

Есть несколько вариантов работы с такими строками: 
* их можно оставить без изменений, если признак, в котором пропущены данные, малозначим;
* можно удалить все строки, в которых есть пустые значения;
* можно заполнить их какими-либо значениями (0, медианой или любыми другими константами).

Метод info так же показывает какого типа данные в том или ином столбце: цифровые (int или float), текстовые и т.д. В последней строке указан объем памяти, которую занимает датафрейм. При больших объемах данных это позволяет оценить хватит ли вам ресурсов для загрузки в память полного датасета

Еще один полезный метод для начального анализа данных - метод describe(), который выдает краткую статистику по числовым признакам: среднее, стандартное отклонение, минимум, максимум, медианы, квартили и т.д. Самостоятельно посмотрите, что означает каждое понятие. 

In [0]:
df.describe()

##Доступ к элементам данных

###Доступ к элементам DataFrame

Разберемся как посмотреть какие-то конкретные значения в датафрейме. Наш датафрейм представляет собой таблицу, состоящую из строк и столбцов. Обратиться к конкретному столбцу можно используя его имя. Например, выведем первые 10 строк из столбца с возрастом пассажиров

In [0]:
df['Age'].head(10)

Второй способ обращения - через "."

In [0]:
df.Age.head(10)

Столбец таблицы - это объек Pandas Series, убедимся в этом определив тип полученного объекта. Этот объект проиндексирован (слева печатаются индексы). В нижней строке есть информацию о его имени и типе значений.
Кроме того, здесь хорошо видны пропуски (незаполненные значения) в некоторых строках (они обозначены NaN - Not-A-Number)

In [0]:
type(df['Age'])

Кроме обращения к столбцу по имени, можно использовать индексацию с помощью методов loc и iloc

Метод loc выдает нам подматрицу, используя индексы строк и столбцов. Первый аргумент отвечает за количество записей (как с начала, так и при желании с любого места), а второй - за отраженные в подматрице признаки.


In [0]:
df.loc[0:5, ['Pclass', 'Fare']]

Метод iloc работает схожим образом, за исключением того, что второй аргумент теперь тоже индексы, то есть отражает количество признаков.


In [0]:
df.iloc[0:5, 1:3]

# Доступ к элементам Series

Для примера создадим два объекта Series

In [0]:
s1 = pd.Series(["one", "two", "three", "four", "five"]) # передаем список, индексы проставляются автоматически с 0
print(s1)

In [0]:
s2 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])  # передаем список, индексы заданы символами от 'a' до 'e'
print(s2)

К элементам Series можно обращаться по численному индексу через "[ ]"

In [0]:
s2[2] # второй элемент серии s2 (индексация с 0)

К элементам Series можно обращаться по метке:

In [0]:
s2['c']

К элементам Series можно применять так называемые slice (срезы) через ':'.
Срезами является часть серии до или после определенного элемента

In [0]:
s2[:2] # все элементы до второго включительно

In [0]:
s2[2:] # второй и все элементы после второго до конца

In [0]:
s2[2:4] # все элементы со второго по четвертый не включительно. Последний никогда не включается.

In [0]:
s2[:] # все элементы

В поле для индекса можно поместить условное выражение.
Данное выражение можно перевести как вопрос, является ли значение элемента (признака) меньшим или равным двум.

In [0]:
s2[s2 <= 2]

Или даже несколько условных выражений, отделенных "( )". 

Если соединить два условия знаком "&", то результат будет удовлетворять двум условиям, а если знаком "|", то хотя бы одному из них.

In [0]:
s2[(s2 >= 2) & (s2 <=4)]

In [0]:
s2[(s2 <= 2) | (s2 == 5)]

Важно, что в условных выражениях равенство пишется как "==" (два знака "равно").

Со структурами Series можно работать как с векторами: складывать, умножать вектор на число и т.п.

In [0]:
s3 = s2 + 10

In [0]:
print(s3)

## Примеры анализа информации

Для примера отберем пассажиров мужского пола, возраст которых меньше сорока лет.

In [0]:
df[(df['Sex'] == 'male') & (df.Age < 40)].head(5)

Можно отсортировать этих людей по возрастанию платы за билет. Ascending в данной функции отвечает за сортировку по убыванию (False) или по возрастанию (True).

In [0]:
df[(df['Sex'] == 'male') & (df.Age < 40)].sort_values(by='Fare',ascending=True).head(10)

Можно подсчитать количество пассажиров (а точнее их уникальных номеров) с помощью функции count()

In [0]:
df[(df['Sex'] == 'male') & (df.Age < 40)].sort_values(by='Fare',ascending=True).PassengerId.count()

Также можно быстро вывести распределение переменной Sex с помощью функции value_count()

In [ ]:
df.Sex.value_counts()

## Задания

In [2]:
import pandas as pd
df = pd.read_csv('titanic_train.csv')
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [3]:
df.Age.min()

0.42

### 21. Сколько человек спаслись и сколько погибли?

In [34]:
df.Survived.value_counts()
# 0 - Погибли, 1 - Спаслись

0    549
1    342
Name: Survived, dtype: int64

### 22. Выведите распределение переменной Survived отдельно для мужчин и отдельно для женщин


In [35]:
df[(df['Sex'] == 'male')].Survived.value_counts()
# 0 - Погибли, 1 - Спаслись

0    468
1    109
Name: Survived, dtype: int64

In [36]:
df[(df['Sex'] == 'female')].Survived.value_counts()
# 0 - Погибли, 1 - Спаслись

1    233
0     81
Name: Survived, dtype: int64

### 23. Каковы медиана и стандартное отклонение цен за билет?

In [37]:
df.Fare.median()

14.4542

In [38]:
df.Fare.std()

49.693428597180905

### 24. Подсчитайте долю выживших среди людей моложе 25 лет и старше 55.

In [39]:
all = df[(df.Age < 25) | (df.Age > 55)].PassengerId.count() 
alive = df[(df['Survived'] == 1) & ((df.Age < 25) | (df.Age > 55))].Survived.value_counts() 
alive / all

1    0.408805
Name: Survived, dtype: float64

### 25. Подсчитайте долю выживших среди мужчин и женщин.

In [40]:
allmen = df[(df['Sex'] == "male")].PassengerId.count()
alivemen = df[(df['Sex'] == 'male') & (df['Survived'] == 1)].Survived.value_counts()
alivemen / allmen

1    0.188908
Name: Survived, dtype: float64

In [41]:
allwomen = df [(df['Sex'] == "female")].PassengerId.count()
alivewomen = df[(df['Sex'] == 'female') & (df['Survived'] == 1)].Survived.value_counts()
alivewomen / allwomen

1    0.742038
Name: Survived, dtype: float64

### 26. В каком городе больше всего село пассажиров?

In [42]:
df.groupby(['Embarked']).PassengerId.count()

Embarked
C    168
Q     77
S    644
Name: PassengerId, dtype: int64

### 27. Подсчитайте средний возраст выживших

In [43]:
df[(df['Survived'] == 1)].Age.mean()

28.343689655172415

### 28. Подсчитайте средний возраст пассажиров каждого из трех классов


In [44]:
df[(df['Pclass'] == 3)].Age.mean()

25.14061971830986

In [45]:
df[(df['Pclass'] == 2)].Age.mean()

29.87763005780347

In [46]:
df[(df['Pclass'] == 1)].Age.mean()

38.233440860215055

### 29. Подсчитайте средний возраст выживших мужчин, купивших билет во 2 класс

In [47]:
df[(df['Sex'] == 'male') & (df['Survived'] == 1) & (df['Pclass'] == 2)].Age.mean()

16.022

### 30. Оцените, как влияет на выживаемость пассажиров наличие их родственников на борту.

In [48]:
(df[((df['SibSp'] > 0) | (df['Parch'] > 0)) & (df['Survived'] == 1)].Survived.value_counts())/ df.PassengerId.count() * 100
#percent with relatives

1    20.089787
Name: Survived, dtype: float64

In [49]:
(df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Survived'] == 1)].Survived.value_counts())/ df.PassengerId.count() * 100
#percent without relatives

1    18.294052
Name: Survived, dtype: float64